name: KBS Container Image Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Check
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Build KBS Container Image
      run: |
        DOCKER_BUILDKIT=1 docker build -t kbs:coco-as-grpc . -f Dockerfile.kbs; \
